[variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm cache clean --force",
  "rm -rf node_modules package-lock.json",
  "npm install --omit=dev --no-audit --no-fund"
]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "npm start"
